### ISSUE TITLE
 revme crash

### ISSUE THREAD

**Issue by holiman** [bluealloy/revm#1657]
Copy of https://github.com/holiman/goevmlab/issues/167 

--------

```
root@6db004019665:/# /revme statetest --json /fuzztmp/00000000-mixed-0.json

Running tests in /fuzztmp/00000000-mixed-0.json...
thread 'runner-0' panicked at bins/revme/src/cmd/statetest/models/spec.rs:54:30:
Unknown spec
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
1/1Finished execution. Total CPU time: 0.000000s
Encountered 0 errors out of 1 total tests
Statetest(TestError { name: "thread 0 panicked", kind: Panic })
Error: Statetest(TestError { name: "thread 0 panicked", kind: Panic })
```
```
root@6db004019665:/# RUST_BACKTRACE=1 /revme statetest --json /fuzztmp/00000000-mixed-0.json

Running tests in /fuzztmp/00000000-mixed-0.json...
thread 'runner-0' panicked at bins/revme/src/cmd/statetest/models/spec.rs:54:30:
Unknown spec
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: revme::cmd::statetest::models::spec::SpecName::to_spec_id
   3: revme::cmd::statetest::runner::execute_test_suite
             at ./revm/bins/revme/src/cmd/statetest/runner.rs:328:27
   4: revme::cmd::statetest::runner::run::{{closure}}
             at ./revm/bins/revme/src/cmd/statetest/runner.rs:518:26
   5: core::ops::function::FnOnce::call_once
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
1/1Finished execution. Total CPU time: 0.000000s
Encountered 0 errors out of 1 total tests
Statetest(TestError { name: "thread 0 panicked", kind: Panic })
Error: Statetest(TestError { name: "thread 0 panicked", kind: Panic })
```
testfile
```json
{"00000000-mixed-0":{"env":{"currentCoinbase":"b94f5374fce5edbc8e2a8697c15331677e6ebf0b","currentDifficulty":"0x200000","currentRandom":"0x0000000000000000000000000000000000000000000000000000000000200000","currentGasLimit":"0x26e1f476fe1e22","currentNumber":"0x1","currentTimestamp":"0x3e8","previousHash":"0x044852b2a670ade5407e78fb2863c51de9fcb96542a07186fe3aeda6bb8a116d","currentBaseFee":"0x10"},"pre":{"0x000000000000000000000000000000000000d0de":{"code":"0x7ee8e8e8e2000100000009ea02000000000000ff3ffffff800000010002280ff51760fffc000000000000767676240000000000002b05760476780000000000000017f7effffff8000000000000000000000000000000000000000d9000000000000017a010900000000000000000000000000000000000000000000000000903c778000000000000000800000000000000080000000000000007ee8e8e8e2000100000009ea02000000000000ff3ffffff800000010002200009020905268066aa0a5319bcf5cb46a1000000000000000000000f3","storage":{},"balance":"0x0","nonce":"0x0"},"0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b":{"code":"0x","storage":{},"balance":"0xffffffffff","nonce":"0x0"}},"transaction":{"gasPrice":"0x10","nonce":"0x0","to":"0x000000000000000000000000000000000000d0De","data":["0x7a4c68b6958e155e01aa2b41463782ef6a68b4d3"],"gasLimit":["0xf42400"],"value":["0x11"],"sender":"0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b","secretKey":"0x45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8"},"out":"0x","post":{"Merge":[{"hash":"0x0000000000000000000000000000000000000000000000000000000000000000","logs":"0x0000000000000000000000000000000000000000000000000000000000000000","indexes":{"data":0,"gas":0,"value":0}}]}}}
```
cc @rakita

**Comment by rakita** [comment]
Yeah, will fix it right away. It slipped my mind.

`Merge` was renamed to `Paris` as all `ethereum/tests` are using `Paris` hardfork. Panic was intentional so there is hard notice that the new hardfork is noticed.
