### ISSUE TITLE
Overflow in gas calculation when running state tests in debug mode

### ISSUE THREAD

**Issue by sveitser** [bluealloy/revm#186]
On commit 03413f063bb87bbc6f48040fc54eb778a2726d9b

```
env RUST_BACKTRACE=full cargo run -p revme -- statetest ethtests/GeneralStateTests
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/revme statetest ethtests/GeneralStateTests`
Start running tests on: "ethtests/GeneralStateTests"
████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1044/2606
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/lulu/r/bluealloy/revm/crates/revm/src/gas/calc.rs:24:25
stack backtrace:
   0:     0x55adc52dd7ed - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55adc52dd7ed - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55adc52dd7ed - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55adc52dd7ed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55adc5300bfc - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x55adc52d8181 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x55adc52defe5 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55adc52defe5 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55adc52defe5 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x55adc52dec59 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x55adc52df5b8 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x55adc52df429 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:586:13
  12:     0x55adc52ddca4 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55adc52df199 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x55adc4268153 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x55adc426801d - core::panicking::panic::hab046c3856b52f65
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:48:5
  16:     0x55adc4337107 - revm::gas::calc::sstore_refund::h026c187907cc0973
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/gas/calc.rs:24:25
  17:     0x55adc4464cdb - revm::instructions::host::sstore::hc76aa1d8e049a9ca
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/instructions/host.rs:122:21
  18:     0x55adc4597cec - revm::instructions::eval::h1cc512d2ae08c3b9
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/instructions.rs:231:27
  19:     0x55adc4597cec - revm::interpreter::Interpreter::run::ha402f5baae9c1638
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/interpreter.rs:126:19
  20:     0x55adc46600da - revm::evm_impl::EVMImpl<GSPEC,DB,_>::call_inner::ha22a04fb97dbc8e8
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/evm_impl.rs:612:31
  21:     0x55adc46dc22a - <revm::evm_impl::EVMImpl<GSPEC,DB,_> as revm::evm_impl::Host>::call::h2d2efb57dda3e6df
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/evm_impl.rs:730:9
  22:     0x55adc43d6ead - revm::instructions::host::call::h710fcb07464e37bb
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/instructions/host.rs:379:9
  23:     0x55adc4597e5c - revm::instructions::eval::h1cc512d2ae08c3b9
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/instructions.rs:241:25
  24:     0x55adc4597e5c - revm::interpreter::Interpreter::run::ha402f5baae9c1638
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/interpreter.rs:126:19
  25:     0x55adc46a19b5 - revm::evm_impl::EVMImpl<GSPEC,DB,_>::create_inner::h9d64f0c765e74bba
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/evm_impl.rs:439:27
  26:     0x55adc46f9395 - <revm::evm_impl::EVMImpl<GSPEC,DB,_> as revm::evm_impl::Transact>::transact::hfb153400b7f5f380
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/evm_impl.rs:157:55
  27:     0x55adc432d2c4 - revm::evm::EVM<DB>::transact::h0f54e493397e3225
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/evm.rs:64:23
  28:     0x55adc432cc00 - revm::evm::EVM<DB>::transact_commit::h8ae6738fc0114e37
                               at /home/lulu/r/bluealloy/revm/crates/revm/src/evm.rs:47:36
  29:     0x55adc472cce4 - revme::statetest::runner::execute_test_suit::h6e2bfe7a6abaeec9
                               at /home/lulu/r/bluealloy/revm/bins/revme/src/statetest/runner.rs:224:21
  30:     0x55adc42bb213 - revme::statetest::runner::run::{{closure}}::hd2ce916e71f976b6
                               at /home/lulu/r/bluealloy/revm/bins/revme/src/statetest/runner.rs:298:39
  31:     0x55adc42fd90e - std::sys_common::backtrace::__rust_begin_short_backtrace::hab7a3ec2e486b47a
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:122:18
  32:     0x55adc4479fa8 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h995dadf9c44ea92a
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/mod.rs:501:17
  33:     0x55adc462d429 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h83054bb44d82ce28
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panic/unwind_safe.rs:271:9
  34:     0x55adc427d16a - std::panicking::try::do_call::h19ef3beee3bdb4dd
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  35:     0x55adc427d35b - __rust_try
  36:     0x55adc427cf6e - std::panicking::try::h0c0f9adf06b4c543
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  37:     0x55adc43147c8 - std::panic::catch_unwind::h9c81378a5505f439
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  38:     0x55adc4479cd6 - std::thread::Builder::spawn_unchecked_::{{closure}}::h6dc94284039e3e46
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/mod.rs:500:30
  39:     0x55adc46224ce - core::ops::function::FnOnce::call_once{{vtable.shim}}::heb1cdaf30ca63158
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  40:     0x55adc52e2863 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcbca3baf872b7fe4
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  41:     0x55adc52e2863 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h18790338ce1743e2
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  42:     0x55adc52e2863 - std::sys::unix::thread::Thread::new::thread_start::hb1067183bad48893
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7fb78c0a8ff2 - start_thread
  44:     0x7fb78c12bbfc - clone3
████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1048/2606
Error: Statetest(SystemError)
```

**Comment by sveitser** [comment]
I found at least the following two tests to trigger it

```
ethtests/GeneralStateTests/stSStoreTest/sstore_changeFromExternalCallInInitCode.json
ethtests/GeneralStateTests/stSStoreTest/sstore_Xto0toXto0.json
```

**Comment by rakita** [comment]
Introduced yesterday: https://github.com/bluealloy/revm/pull/180 will revert it.

@shekhirin I probably used i64 bcs of this 😅

**Comment by gakonst** [comment]
can close i think https://github.com/bluealloy/revm/commit/7ecc92095c14566a264df790cf9f8792a3341b22
