### ISSUE TITLE
Integer overflow while calculating the remaining gas in GasInspector

### ISSUE THREAD

**Issue by pcy190** [bluealloy/revm#277]
The `reduced_gas_block` in `GasInspector` doesn't be cleared properly in the `step_end` handler. 

Therefore, `interp.gas.remaining() + self.full_gas_block` may less than `reduced_gas_block`, which results in integer underflow in the following line:

https://github.com/bluealloy/revm/blob/4ef7446f9c26d91702c349977567255624caabcb/crates/revm/src/inspector.rs#L210

To reproduce the overflow case, please use the following code snippet:

```rust
let mut evm = revm::new();
let mut database = revm::InMemoryDB::default();
let code: Bytes = hex::decode("5b597fb075978b6c412c64d169d56d839a8fe01b3f4607ed603b2c78917ce8be1430fe6101e8527ffe64706ecad72a2f5c97a95e006e279dc57081902029ce96af7edae5de116fec610208527f9fc1ef09d4dd80683858ae3ea18869fe789ddc365d8d9d800e26c9872bac5e5b6102285260276102485360d461024953601661024a53600e61024b53607d61024c53600961024d53600b61024e5360b761024f5360596102505360796102515360a061025253607261025353603a6102545360fb61025553601261025653602861025753600761025853606f61025953601761025a53606161025b53606061025c5360a661025d53602b61025e53608961025f53607a61026053606461026153608c6102625360806102635360d56102645360826102655360ae61026653607f6101e8610146610220677a814b184591c555735fdcca53617f4d2b9134b29090c87d01058e27e962047654f259595947443b1b816b65cdb6277f4b59c10a36f4e7b8658f5a5e6f5561").unwrap().into();

let acc_info = revm::AccountInfo {
    balance: "0x100c5d668240db8e00".parse().unwrap(),
    code_hash: H256::from_slice(Keccak256::digest(&code).as_slice()),
    code: Some(Bytecode::new_raw(code.clone())),
    nonce: "1".parse().unwrap(),
};
let callee = "0x5fdcca53617f4d2b9134b29090c87d01058e27e9";
database.insert_account_info(H160::from_str(callee).unwrap(), acc_info);
evm.database(database);
evm.env.tx.caller = H160::from_str("0x5fdcca53617f4d2b9134b29090c87d01058e27e0").unwrap();
evm.env.tx.transact_to = TransactTo::Call(H160::from_str(callee).unwrap());
evm.env.tx.data = Bytes::from(hex::decode("").unwrap());
evm.env.tx.value = U256::try_from(0).unwrap();
evm.inspect_commit(CustomPrintTracer::new());
```

In debug mode, the revme crashed with `attempt to subtract with overflow`, while in release mode, the remaining gas grew with an incorrect value:

```
attempt to subtract with overflow
thread 'statetest::runner::tests::test' panicked at 'attempt to subtract with overflow', /revm/crates/revm/src/inspector.rs:210:30
stack backtrace:
    0: rust_begin_unwind
    1: core::panicking::panic_fmt
    2: core::panicking::panic
    3: <revm::inspector::GasInspector as revm::inspector::Inspector<DB>>::step_end
    at /revm/crates/revm/src/inspector.rs:210:30
```

**Comment by rakita** [comment]
This seems like a bug, but will need it to look a bit in detail later.

Thank you for reporting and for the reproducible example, it helps a lot!

**Comment by rakita** [comment]
Fixed. Thank you for reporting!
