### ISSUE TITLE
Build failed: `c-kzg-0.4.0`

### ISSUE THREAD

**Issue by mrLSD** [bluealloy/revm#919]
## Description

Failed to build with environment:

➡️ On MacOs: `14.2`
➡️ Clang:
```
Homebrew clang version 17.0.6
Target: arm64-apple-darwin23.2.0
```
➡️ Rust: rustc 1.74.1 (a28077b28 2023-12-04)

```
cargo build --release 
```

### Output
```
    Checking ethabi v18.0.0
    Checking open-fastrlp v0.1.4
    Checking utf-8 v0.7.6
    Checking untrusted v0.7.1
error: failed to run custom build command for `c-kzg v0.4.0`

Caused by:
  process didn't exit successfully: `/Users/evgeny/dev/rs/revm/target/debug/build/c-kzg-ab3acbaa76308a75/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "/Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/blst/bindings" "-o" "/Users/evgeny/dev/rs/revm/target/debug/build/c-kzg-744881c6d4e8b10e/out/8d4c21fdf7a4f15b-c_kzg_4844.o" "-c" "/Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/src/c_kzg_4844.c"
  exit status: 0
  cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
  AR_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
  AR_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64-apple-darwin
  ARFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64_apple_darwin
  ARFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  running: ZERO_AR_DATE="1" "ar" "cq" "/Users/evgeny/dev/rs/revm/target/debug/build/c-kzg-744881c6d4e8b10e/out/libckzg.a" "/Users/evgeny/dev/rs/revm/target/debug/build/c-kzg-744881c6d4e8b10e/out/8d4c21fdf7a4f15b-c_kzg_4844.o"
  exit status: 0
  running: "ar" "s" "/Users/evgeny/dev/rs/revm/target/debug/build/c-kzg-744881c6d4e8b10e/out/libckzg.a"
  exit status: 0
  cargo:rustc-link-lib=static=ckzg
  cargo:rustc-link-search=native=/Users/evgeny/dev/rs/revm/target/debug/build/c-kzg-744881c6d4e8b10e/out
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_darwin
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  /Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/src/c_kzg_4844.h:27:10: fatal error: 'stdio.h' file not found
  thread 'main' panicked at /Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/build.rs:130:10:
  called `Result::unwrap()` on an `Err` value: ClangDiagnostic("/Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/src/c_kzg_4844.h:27:10: fatal error: 'stdio.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
evgeny@Evgenys-MacBook-Pro revm % time cargo build --release      
evgeny@Evgenys-MacBook-Pro revm % 
evgeny@Evgenys-MacBook-Pro revm % rustc -V
rustc 1.74.1 (a28077b28 2023-12-04)
evgeny@Evgenys-MacBook-Pro revm % rustup update
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: syncing channel updates for 'nightly-aarch64-apple-darwin'
info: latest update on 2023-12-19, rust version 1.76.0-nightly (3f28fe133 2023-12-18)
info: downloading component 'rust-src'
  2.5 MiB /   2.5 MiB (100 %)   1.2 MiB/s in  2s ETA:  0s
info: downloading component 'cargo'
  6.6 MiB /   6.6 MiB (100 %) 1003.9 KiB/s in  8s ETA:  0s
info: downloading component 'clippy'
  2.0 MiB /   2.0 MiB (100 %) 364.7 KiB/s in  6s ETA:  0s
info: downloading component 'rust-std'
 24.3 MiB /  24.3 MiB (100 %) 1021.9 KiB/s in 27s ETA:  0s
info: downloading component 'rustc'
 49.8 MiB /  49.8 MiB (100 %)   1.2 MiB/s in 48s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'rust-src'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'rust-src'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-std'
 24.3 MiB /  24.3 MiB (100 %)  19.5 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 49.8 MiB /  49.8 MiB (100 %)  21.6 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'
info: checking for self-update

  stable-aarch64-apple-darwin unchanged - rustc 1.74.1 (a28077b28 2023-12-04)
   nightly-aarch64-apple-darwin updated - rustc 1.76.0-nightly (3f28fe133 2023-12-18) (from rustc 1.76.0-nightly (503e12932 2023-12-07))

info: cleaning up downloads & tmp directories
evgeny@Evgenys-MacBook-Pro revm % ls
CHANGELOG.md	LICENSE		bins		documentation
Cargo.lock	README.md	book.toml	examples
Cargo.toml	assets		crates		target
evgeny@Evgenys-MacBook-Pro revm % rustc -V
rustc 1.74.1 (a28077b28 2023-12-04)
evgeny@Evgenys-MacBook-Pro revm % time cargo build --release      
   Compiling c-kzg v0.4.0
   Compiling secp256k1-sys v0.9.0
   Compiling secp256k1 v0.28.0
error: failed to run custom build command for `c-kzg v0.4.0`

Caused by:
  process didn't exit successfully: `/Users/evgeny/dev/rs/revm/target/release/build/c-kzg-4f72a952f899a37d/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "/Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/blst/bindings" "-o" "/Users/evgeny/dev/rs/revm/target/release/build/c-kzg-523f4371376d6f81/out/8d4c21fdf7a4f15b-c_kzg_4844.o" "-c" "/Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/src/c_kzg_4844.c"
  exit status: 0
  cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
  AR_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
  AR_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64-apple-darwin
  ARFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64_apple_darwin
  ARFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  running: ZERO_AR_DATE="1" "ar" "cq" "/Users/evgeny/dev/rs/revm/target/release/build/c-kzg-523f4371376d6f81/out/libckzg.a" "/Users/evgeny/dev/rs/revm/target/release/build/c-kzg-523f4371376d6f81/out/8d4c21fdf7a4f15b-c_kzg_4844.o"
  exit status: 0
  running: "ar" "s" "/Users/evgeny/dev/rs/revm/target/release/build/c-kzg-523f4371376d6f81/out/libckzg.a"
  exit status: 0
  cargo:rustc-link-lib=static=ckzg
  cargo:rustc-link-search=native=/Users/evgeny/dev/rs/revm/target/release/build/c-kzg-523f4371376d6f81/out
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_darwin
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  /Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/src/c_kzg_4844.h:27:10: fatal error: 'stdio.h' file not found
  thread 'main' panicked at /Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/build.rs:130:10:
  called `Result::unwrap()` on an `Err` value: ClangDiagnostic("/Users/evgeny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/c-kzg-0.4.0/c-kzg-sys/src/c_kzg_4844.h:27:10: fatal error: 'stdio.h' file not found\n")

```

**Comment by rakita** [comment]
Closing this, would assume it worked for you
